version: "3.2"
services:
   
  sql-server-db:
    container_name: ${CONTAINER_DB}
    build:
      context: .
      dockerfile: DockerfileDataBase
    restart: "always"
    ports:
      - "1433:1433"
    networks:
      - swagger-network  
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      SA_PASSWORD: ${DB_SA_PASSWORD}
      MSSQL_SA_PASSWORD: ${DB_SA_PASSWORD}
      ACCEPT_EULA: "Y"

  web-api:
    container_name: ${CONTAINER_API}
    build:
      context: .
      dockerfile: DockerfileWebApi   
    ports:
      - 8090:80       
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8090
    volumes:
      - ~/.aspnet/https:/https:ro  
    networks:
      - swagger-network
    depends_on:
      - "sql-server-db"
networks: 
    swagger-network:
        driver: bridge