version: "3.2"
services:
   
  sql-server-db:
    container_name: sql-server-db
    build:
      context: .
      dockerfile: DockerfileDataBase
    restart: "always"
    ports:
      - "1433:1433"
    networks:
      - swagger-network  
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      SA_PASSWORD: "sqlserver@2017"
      MSSQL_SA_PASSWORD: "sqlserver@2017"
      ACCEPT_EULA: "Y"

  web-api:
    container_name: swagger-api
    build:
      context: .
      dockerfile: DockerfileWebApi   
    ports:
      - 8090:80
      - 8091:5110     
    networks:
      - swagger-network
    depends_on:
      - "sql-server-db"
networks: 
    swagger-network:
        driver: bridge