version: "3.2"
services:
  sql-server-db:
    container_name: sql-server-db
    build:
      context: .
      dockerfile: Dockerfile
    restart: "always"
    ports:
      - "1433:1433"
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      SA_PASSWORD: "sqlserver@2017"
      MSSQL_SA_PASSWORD: "sqlserver@2017"
      ACCEPT_EULA: "Y"